### ISSUE TITLE
uncaught exception: Highcharts error #13: www.highcharts.com/errors/13

### ISSUE THREAD

**Issue by Snoop** [ecdeveloper/node-web-crawler#16]
uncaught exception: Highcharts error #13: www.highcharts.com/errors/13

something wrong with js

**Comment by ecdeveloper** [comment]
Fixed in new version

**Comment by Shamim-Aktar** [comment]
I am using latest version but its not fixed always showing error #13
